import {
  CheckCircle,
  FolderOpen,
  Schedule,
  Warning,
} from "@mui/icons-material";
import type { ListusersResponse } from "../services/users/users.models";
import type { ColorPriority, ColorStatus } from "../pages/dashboard";

export const mockUsers: ListusersResponse[] = [
  {
    id: "1",
    username: "joao.silva",
    email: "joao.silva@empresa.com",
    company: "Tech Solutions",
    role: 1,
    phone: "+55 11 98765-4321",
    profile_picture: null,
    is_active: true,
    is_email_verified: true,
    created_at: "2024-01-15T10:30:00Z",
    updated_at: "2024-10-20T14:20:00Z",
  },
  {
    id: "2",
    username: "maria.santos",
    email: "maria.santos@startup.com",
    company: "Startup Inovadora",
    role: 2,
    phone: null,
    profile_picture: null,
    is_active: false,
    is_email_verified: true,
    created_at: "2024-03-22T08:15:00Z",
    updated_at: "2024-09-10T16:45:00Z",
  },
  {
    id: "3",
    username: "carlos.oliveira",
    email: "carlos.oliveira@consultoria.com",
    company: "Consultoria Global",
    role: 0,
    phone: "+55 21 99876-5432",
    profile_picture: null,
    is_active: true,
    is_email_verified: false,
    created_at: "2024-02-10T12:00:00Z",
    updated_at: "2024-10-15T09:30:00Z",
  },
  {
    id: "4",
    username: "ana.costa",
    email: "ana.costa@designhub.io",
    company: "Design Hub",
    role: 2,
    phone: "+55 31 98412-8876",
    profile_picture: null,
    is_active: true,
    is_email_verified: true,
    created_at: "2024-04-05T11:22:00Z",
    updated_at: "2024-10-05T18:40:00Z",
  },
  {
    id: "5",
    username: "pedro.lima",
    email: "pedro.lima@datawave.ai",
    company: "DataWave AI",
    role: 1,
    phone: "+55 41 99932-1122",
    profile_picture: null,
    is_active: false,
    is_email_verified: false,
    created_at: "2024-05-18T15:12:00Z",
    updated_at: "2024-09-29T10:05:00Z",
  },
  {
    id: "6",
    username: "lucas.almeida",
    email: "lucas.almeida@infotec.com",
    company: "Infotec",
    role: 0,
    phone: "+55 85 98123-4455",
    profile_picture: null,
    is_active: true,
    is_email_verified: true,
    created_at: "2024-06-11T09:40:00Z",
    updated_at: "2024-10-18T13:22:00Z",
  },
  {
    id: "7",
    username: "juliana.martins",
    email: "juliana.martins@meditech.com",
    company: "MediTech",
    role: 1,
    phone: "+55 62 99773-9821",
    profile_picture: null,
    is_active: true,
    is_email_verified: true,
    created_at: "2024-07-01T13:55:00Z",
    updated_at: "2024-10-22T09:15:00Z",
  },
  {
    id: "8",
    username: "felipe.rocha",
    email: "felipe.rocha@greenenergy.com",
    company: "Green Energy",
    role: 2,
    phone: null,
    profile_picture: null,
    is_active: false,
    is_email_verified: false,
    created_at: "2024-08-09T07:25:00Z",
    updated_at: "2024-09-30T20:05:00Z",
  },
  {
    id: "9",
    username: "beatriz.fernandes",
    email: "beatriz.fernandes@nextvision.com",
    company: "NextVision",
    role: 0,
    phone: "+55 27 98876-0033",
    profile_picture: null,
    is_active: true,
    is_email_verified: true,
    created_at: "2024-09-12T10:00:00Z",
    updated_at: "2024-10-21T08:10:00Z",
  },
  {
    id: "10",
    username: "rafael.mendes",
    email: "rafael.mendes@cloudsystems.io",
    company: "Cloud Systems",
    role: 1,
    phone: "+55 92 98765-2211",
    profile_picture: null,
    is_active: false,
    is_email_verified: true,
    created_at: "2024-10-01T14:45:00Z",
    updated_at: "2024-10-19T17:35:00Z",
  },
];

export type ProjectTypes = {
  id: number;
  name: string;
  progress: number;
  status: ColorStatus;
  deadline: string;
  team: string[];
  priority: ColorPriority;
};
export const projects: ProjectTypes[] = [
  {
    id: 1,
    name: "Redesign do Website",
    progress: 75,
    status: "Em Progresso",
    deadline: "15 Nov 2025",
    team: ["A", "B", "C"],
    priority: "Alta",
  },
  {
    id: 2,
    name: "App Mobile v2.0",
    progress: 45,
    status: "Em Progresso",
    deadline: "30 Nov 2025",
    team: ["D", "E"],
    priority: "Média",
  },
  {
    id: 3,
    name: "Sistema de Relatórios",
    progress: 90,
    status: "Revisão",
    deadline: "25 Out 2025",
    team: ["F", "G", "H"],
    priority: "Alta",
  },
  {
    id: 4,
    name: "API de Integração",
    progress: 30,
    status: "Em Progresso",
    deadline: "10 Dez 2025",
    team: ["I", "J"],
    priority: "Baixa",
  },
];

export const recentActivities = [
  {
    id: 1,
    user: "Ana Silva",
    action: "completou a tarefa",
    task: "Design da homepage",
    time: "2h atrás",
  },
  {
    id: 2,
    user: "João Santos",
    action: "comentou em",
    task: "Revisão de código",
    time: "4h atrás",
  },
  {
    id: 3,
    user: "Maria Costa",
    action: "atualizou",
    task: "Documentação API",
    time: "5h atrás",
  },
  {
    id: 4,
    user: "Pedro Lima",
    action: "criou nova tarefa",
    task: "Testes unitários",
    time: "1d atrás",
  },
];

export const stats = [
  {
    label: "Projetos Ativos",
    value: "12",
    icon: FolderOpen,
    color: "#1976d2",
  },
  {
    label: "Tarefas Concluídas",
    value: "147",
    icon: CheckCircle,
    color: "#2e7d32",
  },
  { label: "Em Progresso", value: "23", icon: Schedule, color: "#ed6c02" },
  { label: "Atrasadas", value: "5", icon: Warning, color: "#d32f2f" },
];
