# Generated by Django 5.2.7 on 2025-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenixApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_confirmation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
