# Generated by Django 5.2.7 on 2025-10-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenixApp', '0002_user_locked_until_user_reg_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
